import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider, UIProvider } from "@jamsr-ui/react";
import SessionWrapper from "@/components/SessionWrapper";
import {AuthProvider} from "@/context/AuthContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <SessionWrapper>
        <body
          
        >
          <UIProvider>
            <ToastProvider />
            <AuthProvider>
              
              <div >
                {/* Main content area */}
                {children}
              </div>
            </AuthProvider>
          </UIProvider>
        </body>
      </SessionWrapper>
    </html>
  );
}
